// ============================================================================
// Email Utility Module
// Centralized email templates and sending functionality for L'embrace
// ============================================================================

// ============================================================================
// Types
// ============================================================================

export type EmailLocale = 'en' | 'nl';

export interface SendEmailOptions {
  to: string;
  email: string;
  name: string;
  subject: string;
  html: string;
}

// ============================================================================
// Email Translations
// ============================================================================

const EMAIL_TRANSLATIONS = {
  en: {
    // Base template
    copyLink: 'Or copy and paste this link in your browser:',
    signature: "L'embrace - Elegance in every detail",

    // Password reset
    passwordReset: {
      subject: "Reset your L'embrace password",
      title: 'Reset Your Password',
      body: "You requested to reset your password for your L'embrace account.",
      button: 'Reset Password',
      footer: 'If you did not request this, you can safely ignore this email. Your password will remain unchanged.',
    },

    // Welcome verification
    welcomeVerification: {
      subject: "Verify your L'embrace account",
      title: "Welcome to L'embrace!",
      body: 'Thank you for creating an account. Please verify your email address to complete your registration.',
      button: 'Verify Email Address',
      footer: 'If you did not create this account, you can safely ignore this email.',
    },

    // Resend verification
    resendVerification: {
      subject: "Verify your L'embrace account",
      title: 'Verify Your Email',
      body: "You requested a new verification email for your L'embrace account.",
      button: 'Verify Email Address',
      footer: 'If you did not request this, you can safely ignore this email.',
    },

    // Order confirmation
    orderConfirmation: {
      subject: 'Order confirmation',
      greeting: 'Dear',
      customer: 'Customer',
      thankYou: 'Thank you for your order! Your payment has been successfully processed and your order is now being prepared.',
      orderDetails: 'Order Details:',
      orderNumber: 'Order number:',
      date: 'Date:',
      shippingMethod: 'Shipping method:',
      expressDelivery: 'Express delivery',
      standardDelivery: 'Standard delivery',
      expectedDelivery: 'Expected delivery:',
      shippingAddress: 'Shipping Address:',
      billingAddress: 'Billing Address:',
      orderedItems: 'Ordered Items:',
      noItems: 'No items found',
      priceOverview: 'Price Overview:',
      subtotal: 'Subtotal:',
      shippingCost: 'Shipping cost:',
      total: 'Total:',
      nextSteps: 'Next Steps:',
      step1: 'We will process your order and prepare it for shipping',
      step2: 'You will receive an email once your package has been shipped with tracking information',
      step3: 'Your package will be delivered to the specified address',
      questions: 'Do you have questions about your order? Feel free to contact us!',
      regards: 'Best regards,',
      team: "The L'embrace Team",
      autoGenerated: 'This email was automatically generated. Please do not reply to this email address.',
    },

    // Seller notification
    sellerNotification: {
      subject: 'New order received',
      title: '🚨 New Order Received',
      intro: 'A new order has been received that requires immediate attention!',
      orderDetails: '📋 Order Details:',
      orderNumber: 'Order number:',
      date: 'Date:',
      time: 'Time:',
      shippingMethod: 'Shipping method:',
      expressDelivery: 'Express delivery',
      standardDelivery: 'Standard delivery',
      expectedDelivery: 'Expected delivery:',
      customerInfo: '👤 Customer Information:',
      name: 'Name:',
      email: 'Email:',
      phone: 'Phone:',
      notProvided: 'Not provided',
      shippingAddress: '📍 Shipping Address:',
      billingAddress: '📍 Billing Address:',
      orderedItems: '🛍️ Ordered Items:',
      noItems: 'No items found',
      priceOverview: '💰 Price Overview:',
      subtotal: 'Subtotal:',
      shippingCost: 'Shipping cost:',
      total: 'Total:',
      actionRequired: '⚡ Action Required:',
      action1: 'Check the order in the admin panel',
      action2: 'Prepare the items for shipping',
      action3: 'Send tracking information to the customer once shipped',
      action4: 'Update the order status if needed',
      warning: '⚠️ Note: This order requires immediate processing to meet the expected delivery date.',
      autoGenerated: "This notification was automatically generated by the L'embrace system.",
    },

    // Order shipped
    orderShipped: {
      subject: 'Your order is on its way!',
      title: '📦 Your Order Has Been Shipped!',
      greeting: 'Dear',
      customer: 'Customer',
      intro: 'Great news! Your order has been shipped and is on its way to you.',
      orderDetails: 'Order Details:',
      orderNumber: 'Order number:',
      shippedDate: 'Shipped on:',
      shippingAddress: 'Shipping Address:',
      whatNext: 'What happens next?',
      step1: 'Your package is now with our delivery partner',
      step2: 'You can expect delivery within 1-3 business days',
      step3: 'Keep an eye on your mailbox!',
      questions: 'Questions about your delivery? Feel free to contact us!',
      regards: 'Best regards,',
      team: "The L'embrace Team",
      autoGenerated: 'This email was automatically generated. Please do not reply to this email address.',
    },
  },
  nl: {
    // Base template
    copyLink: 'Of kopieer en plak deze link in je browser:',
    signature: "L'embrace - Elegantie in elk detail",

    // Password reset
    passwordReset: {
      subject: "Herstel je L'embrace wachtwoord",
      title: 'Herstel Je Wachtwoord',
      body: "Je hebt verzocht om het wachtwoord van je L'embrace account te resetten.",
      button: 'Wachtwoord Herstellen',
      footer: 'Als je dit niet hebt aangevraagd, kun je deze e-mail veilig negeren. Je wachtwoord blijft ongewijzigd.',
    },

    // Welcome verification
    welcomeVerification: {
      subject: "Verifieer je L'embrace account",
      title: "Welkom bij L'embrace!",
      body: 'Bedankt voor het aanmaken van een account. Verifieer je e-mailadres om je registratie te voltooien.',
      button: 'E-mailadres Verifiëren',
      footer: 'Als je dit account niet hebt aangemaakt, kun je deze e-mail veilig negeren.',
    },

    // Resend verification
    resendVerification: {
      subject: "Verifieer je L'embrace account",
      title: 'Verifieer Je E-mail',
      body: "Je hebt een nieuwe verificatie e-mail aangevraagd voor je L'embrace account.",
      button: 'E-mailadres Verifiëren',
      footer: 'Als je dit niet hebt aangevraagd, kun je deze e-mail veilig negeren.',
    },

    // Order confirmation
    orderConfirmation: {
      subject: 'Bestelling bevestiging',
      greeting: 'Beste',
      customer: 'Klant',
      thankYou: 'Bedankt voor je bestelling! Je betaling is succesvol verwerkt en je bestelling wordt nu voorbereid.',
      orderDetails: 'Bestelling Details:',
      orderNumber: 'Bestelnummer:',
      date: 'Datum:',
      shippingMethod: 'Verzendmethode:',
      expressDelivery: 'Express levering',
      standardDelivery: 'Standaard levering',
      expectedDelivery: 'Verwachte levering:',
      shippingAddress: 'Verzendadres:',
      billingAddress: 'Factuuradres:',
      orderedItems: 'Bestelde Items:',
      noItems: 'Geen items gevonden',
      priceOverview: 'Prijs Overzicht:',
      subtotal: 'Subtotaal:',
      shippingCost: 'Verzendkosten:',
      total: 'Totaal:',
      nextSteps: 'Volgende Stappen:',
      step1: 'We verwerken je bestelling en bereiden deze voor op verzending',
      step2: 'Je ontvangt een e-mail zodra je pakket is verzonden met tracking informatie',
      step3: 'Je pakket wordt geleverd op het opgegeven adres',
      questions: 'Heb je vragen over je bestelling? Neem gerust contact met ons op!',
      regards: 'Met vriendelijke groet,',
      team: "Het L'embrace Team",
      autoGenerated: 'Deze e-mail is automatisch gegenereerd. Reageer niet op dit e-mailadres.',
    },

    // Seller notification
    sellerNotification: {
      subject: 'Nieuwe bestelling ontvangen',
      title: '🚨 Nieuwe Bestelling Ontvangen',
      intro: 'Er is een nieuwe bestelling binnengekomen die directe aandacht vereist!',
      orderDetails: '📋 Bestelling Details:',
      orderNumber: 'Bestelnummer:',
      date: 'Datum:',
      time: 'Tijd:',
      shippingMethod: 'Verzendmethode:',
      expressDelivery: 'Express levering',
      standardDelivery: 'Standaard levering',
      expectedDelivery: 'Verwachte levering:',
      customerInfo: '👤 Klant Informatie:',
      name: 'Naam:',
      email: 'E-mail:',
      phone: 'Telefoon:',
      notProvided: 'Niet opgegeven',
      shippingAddress: '📍 Verzendadres:',
      billingAddress: '📍 Factuuradres:',
      orderedItems: '🛍️ Bestelde Items:',
      noItems: 'Geen items gevonden',
      priceOverview: '💰 Prijs Overzicht:',
      subtotal: 'Subtotaal:',
      shippingCost: 'Verzendkosten:',
      total: 'Totaal:',
      actionRequired: '⚡ Actie Vereist:',
      action1: 'Controleer de bestelling in het admin panel',
      action2: 'Bereid de items voor op verzending',
      action3: 'Verstuur tracking informatie naar de klant zodra verzonden',
      action4: 'Update de bestelling status indien nodig',
      warning: '⚠️ Let op: Deze bestelling vereist directe verwerking om de verwachte leverdatum te halen.',
      autoGenerated: "Deze notificatie is automatisch gegenereerd door het L'embrace systeem.",
    },

    // Order shipped
    orderShipped: {
      subject: 'Je bestelling is onderweg!',
      title: '📦 Je Bestelling Is Verzonden!',
      greeting: 'Beste',
      customer: 'Klant',
      intro: 'Goed nieuws! Je bestelling is verzonden en is onderweg naar jou.',
      orderDetails: 'Bestelling Details:',
      orderNumber: 'Bestelnummer:',
      shippedDate: 'Verzonden op:',
      shippingAddress: 'Verzendadres:',
      whatNext: 'Wat gebeurt er nu?',
      step1: 'Je pakket is nu bij onze bezorgpartner',
      step2: 'Je kunt de levering binnen 1-3 werkdagen verwachten',
      step3: 'Houd je brievenbus in de gaten!',
      questions: 'Vragen over je levering? Neem gerust contact met ons op!',
      regards: 'Met vriendelijke groet,',
      team: "Het L'embrace Team",
      autoGenerated: 'Deze e-mail is automatisch gegenereerd. Reageer niet op dit e-mailadres.',
    },
  },
} as const;

const getTranslations = (locale: EmailLocale) => EMAIL_TRANSLATIONS[locale] || EMAIL_TRANSLATIONS.en;

export interface EmailTemplateOptions {
  title: string;
  body: string;
  buttonText: string;
  buttonLink: string;
  footerNote?: string;
}

export interface ContactFormData {
  name: string;
  email: string;
  phone?: string;
  message: string;
}

export interface OrderData {
  orderNumber?: string;
  totalPrice: number;
  shippingCost: number;
  customerInfo?: {
    firstname?: string;
    lastname?: string;
    email?: string;
    phone?: string;
  };
  shippingAddress?: {
    street?: string;
    number?: string;
    box?: string;
    postalcode?: string;
    city?: string;
    country?: string;
  };
  billingAddress?: {
    street?: string;
    number?: string;
    box?: string;
    postalcode?: string;
    city?: string;
    country?: string;
  };
  // Legacy field name for backward compatibility
  address?: {
    street?: string;
    number?: string;
    box?: string;
    postalcode?: string;
    city?: string;
    country?: string;
  };
  items?: Array<{
    name: string;
    amount: number;
    calculatedPrice: number;
  }>;
}

// ============================================================================
// Base Email Template
// ============================================================================

const EMAIL_STYLES = {
  container: 'font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;',
  heading: 'color: #333; border-bottom: 2px solid #d4af37; padding-bottom: 10px;',
  body: 'color: #666; line-height: 1.6;',
  buttonContainer: 'text-align: center; margin: 30px 0;',
  button: 'display: inline-block; background-color: #d4af37; color: white; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: bold;',
  linkNote: 'color: #888; font-size: 14px;',
  link: 'color: #d4af37; word-break: break-all; font-size: 14px;',
  divider: 'border: none; border-top: 1px solid #eee; margin: 30px 0;',
  footer: 'color: #888; font-size: 12px;',
  signature: 'color: #666; font-style: italic;',
} as const;

/**
 * Creates a branded email template with consistent styling
 */
export const createEmailTemplate = (options: EmailTemplateOptions & { locale?: EmailLocale }): string => {
  const { title, body, buttonText, buttonLink, footerNote, locale = 'en' } = options;
  const t = getTranslations(locale);

  return `
<div style="${EMAIL_STYLES.container}">
  <h2 style="${EMAIL_STYLES.heading}">${title}</h2>
  <p style="${EMAIL_STYLES.body}">${body}</p>
  <div style="${EMAIL_STYLES.buttonContainer}">
    <a href="${buttonLink}" style="${EMAIL_STYLES.button}">${buttonText}</a>
  </div>
  <p style="${EMAIL_STYLES.linkNote}">${t.copyLink}</p>
  <p style="${EMAIL_STYLES.link}">${buttonLink}</p>
  <hr style="${EMAIL_STYLES.divider}">
  ${footerNote ? `<p style="${EMAIL_STYLES.footer}">${footerNote}</p>` : ''}
  <p style="${EMAIL_STYLES.signature}">${t.signature}</p>
</div>
`.trim();
};

// ============================================================================
// Auth Email Templates
// ============================================================================

/**
 * Creates a password reset email
 */
export const createPasswordResetEmail = (resetLink: string, locale: EmailLocale = 'en'): string => {
  const t = getTranslations(locale).passwordReset;
  return createEmailTemplate({
    title: t.title,
    body: t.body,
    buttonText: t.button,
    buttonLink: resetLink,
    footerNote: t.footer,
    locale,
  });
};

/**
 * Creates a welcome/verification email for new registrations
 */
export const createWelcomeVerificationEmail = (verificationLink: string, locale: EmailLocale = 'en'): string => {
  const t = getTranslations(locale).welcomeVerification;
  return createEmailTemplate({
    title: t.title,
    body: t.body,
    buttonText: t.button,
    buttonLink: verificationLink,
    footerNote: t.footer,
    locale,
  });
};

/**
 * Creates a resend verification email
 */
export const createResendVerificationEmail = (verificationLink: string, locale: EmailLocale = 'en'): string => {
  const t = getTranslations(locale).resendVerification;
  return createEmailTemplate({
    title: t.title,
    body: t.body,
    buttonText: t.button,
    buttonLink: verificationLink,
    footerNote: t.footer,
    locale,
  });
};

// ============================================================================
// Contact Email Template
// ============================================================================

/**
 * Creates a contact form submission email
 */
export const createContactEmailPayload = (formData: ContactFormData, recipientEmail: string = 'info@lembrace.be'): SendEmailOptions => ({
  email: formData.email,
  name: formData.name,
  subject: `New Contact Form Message from ${formData.name}`,
  to: recipientEmail,
  html: `
<h2>Contact Form Submission</h2>

<h3>Contact Details:</h3>
<ul>
  <li><strong>Name:</strong> ${formData.name}</li>
  <li><strong>Email:</strong> ${formData.email}</li>
  <li><strong>Phone:</strong> ${formData.phone || 'Not provided'}</li>
</ul>

<h3>Message:</h3>
<p>${formData.message}</p>

<hr>
<p><em>Sent from L'embrace Contact Form</em></p>
  `.trim(),
});

// ============================================================================
// Order Email Templates
// ============================================================================

/**
 * Formats a date based on locale
 */
const formatDate = (date: Date, locale: EmailLocale = 'en'): string => {
  const localeMap = { en: 'en-US', nl: 'nl-NL' };
  return date.toLocaleDateString(localeMap[locale], {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
};

/**
 * Creates an order confirmation email for customers
 */
export const createOrderConfirmationEmail = (orderData: OrderData, orderNumber: string, locale: EmailLocale = 'en'): string => {
  const t = getTranslations(locale).orderConfirmation;
  const today = formatDate(new Date(), locale);
  const shipAddr = orderData.shippingAddress || orderData.address;
  const billAddr = orderData.billingAddress || shipAddr;

  const itemsHtml = orderData.items?.map((item) => `<li>${item.name} x${item.amount} - €${item.calculatedPrice.toFixed(2)}</li>`).join('') || `<li>${t.noItems}</li>`;

  return `<h2>${t.subject} - ${orderNumber}</h2>

<p>${t.greeting} ${orderData.customerInfo?.firstname || t.customer},</p>

<p>${t.thankYou}</p>

<h3>${t.orderDetails}</h3>
<ul>
  <li><strong>${t.orderNumber}</strong> ${orderNumber}</li>
  <li><strong>${t.date}</strong> ${today}</li>
</ul>

<h3>${t.shippingAddress}</h3>
<p>
  ${orderData.customerInfo?.firstname} ${orderData.customerInfo?.lastname}<br>
  ${shipAddr?.street} ${shipAddr?.number}${shipAddr?.box ? ` bus ${shipAddr.box}` : ''}<br>
  ${shipAddr?.postalcode} ${shipAddr?.city}<br>
  ${shipAddr?.country}
</p>

<h3>${t.billingAddress}</h3>
<p>
  ${orderData.customerInfo?.firstname} ${orderData.customerInfo?.lastname}<br>
  ${billAddr?.street} ${billAddr?.number}${billAddr?.box ? ` bus ${billAddr.box}` : ''}<br>
  ${billAddr?.postalcode} ${billAddr?.city}<br>
  ${billAddr?.country}
</p>

<h3>${t.orderedItems}</h3>
<ul>
  ${itemsHtml}
</ul>

<h3>${t.priceOverview}</h3>
<ul>
  <li><strong>${t.subtotal}</strong> €${(orderData.totalPrice - orderData.shippingCost).toFixed(2)}</li>
  <li><strong>${t.shippingCost}</strong> €${orderData.shippingCost.toFixed(2)}</li>
  <li><strong>${t.total}</strong> €${orderData.totalPrice.toFixed(2)}</li>
</ul>

<h3>${t.nextSteps}</h3>
<ol>
  <li>${t.step1}</li>
  <li>${t.step2}</li>
  <li>${t.step3}</li>
</ol>

<p>${t.questions}</p>

<p>${t.regards}<br>
${t.team}</p>

<hr>
<p><em>${t.autoGenerated}</em></p>`;
};

/**
 * Creates a seller notification email for new orders
 */
export const createSellerNotificationEmail = (orderData: OrderData, orderNumber: string, locale: EmailLocale = 'en'): string => {
  const t = getTranslations(locale).sellerNotification;
  const today = formatDate(new Date(), locale);
  const localeMap = { en: 'en-US', nl: 'nl-NL' };
  const currentTime = new Date().toLocaleTimeString(localeMap[locale], {
    hour: '2-digit',
    minute: '2-digit',
  });
  const shipAddr = orderData.shippingAddress || orderData.address;
  const billAddr = orderData.billingAddress || shipAddr;

  const itemsHtml = orderData.items?.map((item) => `<li><strong>${item.name}</strong> x${item.amount} - €${item.calculatedPrice.toFixed(2)}</li>`).join('') || `<li>${t.noItems}</li>`;

  return `<h2>${t.title} - ${orderNumber}</h2>

<p>${t.intro}</p>

<h3>${t.orderDetails}</h3>
<ul>
  <li><strong>${t.orderNumber}</strong> ${orderNumber}</li>
  <li><strong>${t.date}</strong> ${today}</li>
  <li><strong>${t.time}</strong> ${currentTime}</li>
</ul>

<h3>${t.customerInfo}</h3>
<p>
  <strong>${t.name}</strong> ${orderData.customerInfo?.firstname} ${orderData.customerInfo?.lastname}<br>
  <strong>${t.email}</strong> ${orderData.customerInfo?.email}<br>
  <strong>${t.phone}</strong> ${orderData.customerInfo?.phone || t.notProvided}
</p>

<h3>${t.shippingAddress}</h3>
<p>
  ${orderData.customerInfo?.firstname} ${orderData.customerInfo?.lastname}<br>
  ${shipAddr?.street} ${shipAddr?.number}${shipAddr?.box ? ` bus ${shipAddr.box}` : ''}<br>
  ${shipAddr?.postalcode} ${shipAddr?.city}<br>
  ${shipAddr?.country}
</p>

<h3>${t.billingAddress}</h3>
<p>
  ${orderData.customerInfo?.firstname} ${orderData.customerInfo?.lastname}<br>
  ${billAddr?.street} ${billAddr?.number}${billAddr?.box ? ` bus ${billAddr.box}` : ''}<br>
  ${billAddr?.postalcode} ${billAddr?.city}<br>
  ${billAddr?.country}
</p>

<h3>${t.orderedItems}</h3>
<ul>
  ${itemsHtml}
</ul>

<h3>${t.priceOverview}</h3>
<ul>
  <li><strong>${t.subtotal}</strong> €${(orderData.totalPrice - orderData.shippingCost).toFixed(2)}</li>
  <li><strong>${t.shippingCost}</strong> €${orderData.shippingCost.toFixed(2)}</li>
  <li><strong>${t.total}</strong> €${orderData.totalPrice.toFixed(2)}</li>
</ul>

<h3>${t.actionRequired}</h3>
<ol>
  <li>${t.action1}</li>
  <li>${t.action2}</li>
  <li>${t.action3}</li>
</ol>

<p><strong>${t.warning}</strong></p>

<hr>
<p><em>${t.autoGenerated}</em></p>`;
};

/**
 * Creates an order shipped email for customers
 */
export const createOrderShippedEmail = (orderData: OrderData, orderNumber: string, locale: EmailLocale = 'en'): string => {
  const t = getTranslations(locale).orderShipped;
  const today = formatDate(new Date(), locale);
  const addr = orderData.shippingAddress || orderData.address;

  return `<h2>${t.title}</h2>

<p>${t.greeting} ${orderData.customerInfo?.firstname || t.customer},</p>

<p>${t.intro}</p>

<h3>${t.orderDetails}</h3>
<ul>
  <li><strong>${t.orderNumber}</strong> ${orderNumber}</li>
  <li><strong>${t.shippedDate}</strong> ${today}</li>
</ul>

<h3>${t.shippingAddress}</h3>
<p>
  ${orderData.customerInfo?.firstname} ${orderData.customerInfo?.lastname}<br>
  ${addr?.street} ${addr?.number}${addr?.box ? ` bus ${addr.box}` : ''}<br>
  ${addr?.postalcode} ${addr?.city}<br>
  ${addr?.country}
</p>

<h3>${t.whatNext}</h3>
<ol>
  <li>${t.step1}</li>
  <li>${t.step2}</li>
  <li>${t.step3}</li>
</ol>

<p>${t.questions}</p>

<p>${t.regards}<br>
${t.team}</p>

<hr>
<p><em>${t.autoGenerated}</em></p>`;
};

// ============================================================================
// Email Sending Function
// ============================================================================

/**
 * Sends an email using the Strapi email API
 */
export const sendEmail = async (options: SendEmailOptions, apiUrl: string): Promise<void> => {
  await $fetch(`${apiUrl}/api/email/send`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: options,
  });
};

// ============================================================================
// Helper Functions for Auth Emails
// ============================================================================

/**
 * Sends a password reset email
 */
export const sendPasswordResetEmail = async (email: string, resetToken: string, apiUrl: string, locale: EmailLocale = 'en'): Promise<void> => {
  const t = getTranslations(locale).passwordReset;
  const siteUrl = typeof window !== 'undefined' ? window.location.origin : '';
  const resetLink = `${siteUrl}/reset-password/${resetToken}`;

  await sendEmail(
    {
      to: email,
      email: email,
      name: email,
      subject: t.subject,
      html: createPasswordResetEmail(resetLink, locale),
    },
    apiUrl
  );
};

/**
 * Sends a welcome verification email for new registrations
 */
export const sendWelcomeVerificationEmail = async (email: string, name: string, verificationToken: string, apiUrl: string, locale: EmailLocale = 'en'): Promise<void> => {
  const t = getTranslations(locale).welcomeVerification;
  const siteUrl = typeof window !== 'undefined' ? window.location.origin : '';
  const verificationLink = `${siteUrl}/register/confirmation/${verificationToken}`;

  await sendEmail(
    {
      to: email,
      email: email,
      name: name,
      subject: t.subject,
      html: createWelcomeVerificationEmail(verificationLink, locale),
    },
    apiUrl
  );
};

/**
 * Sends a resend verification email
 */
export const sendResendVerificationEmail = async (email: string, verificationToken: string, apiUrl: string, locale: EmailLocale = 'en'): Promise<void> => {
  const t = getTranslations(locale).resendVerification;
  const siteUrl = typeof window !== 'undefined' ? window.location.origin : '';
  const verificationLink = `${siteUrl}/register/confirmation/${verificationToken}`;

  await sendEmail(
    {
      to: email,
      email: email,
      name: email,
      subject: t.subject,
      html: createResendVerificationEmail(verificationLink, locale),
    },
    apiUrl
  );
};

/**
 * Sends an order confirmation email to the customer
 */
export const sendOrderConfirmationEmail = async (orderData: OrderData, orderNumber: string, apiUrl: string, locale: EmailLocale = 'en'): Promise<void> => {
  const t = getTranslations(locale).orderConfirmation;
  const customerEmail = orderData.customerInfo?.email;
  if (!customerEmail) {
    throw new Error('Customer email is required');
  }

  await sendEmail(
    {
      to: customerEmail,
      email: customerEmail,
      name: orderData.customerInfo?.firstname || t.customer,
      subject: `${t.subject} - ${orderNumber}`,
      html: createOrderConfirmationEmail(orderData, orderNumber, locale),
    },
    apiUrl
  );
};

/**
 * Sends a new order notification email to the seller
 */
export const sendSellerOrderNotification = async (orderData: OrderData, orderNumber: string, apiUrl: string, sellerEmail: string = 'info@lembrace.be', locale: EmailLocale = 'en'): Promise<void> => {
  const t = getTranslations(locale).sellerNotification;
  await sendEmail(
    {
      to: sellerEmail,
      email: sellerEmail,
      name: "L'embrace Team",
      subject: `${t.subject} - ${orderNumber}`,
      html: createSellerNotificationEmail(orderData, orderNumber, locale),
    },
    apiUrl
  );
};

/**
 * Sends an order shipped email to the customer
 */
export const sendOrderShippedEmail = async (orderData: OrderData, orderNumber: string, apiUrl: string, locale: EmailLocale = 'en'): Promise<void> => {
  const t = getTranslations(locale).orderShipped;
  const customerEmail = orderData.customerInfo?.email;
  if (!customerEmail) {
    throw new Error('Customer email is required');
  }

  await sendEmail(
    {
      to: customerEmail,
      email: customerEmail,
      name: orderData.customerInfo?.firstname || t.customer,
      subject: `${t.subject} - ${orderNumber}`,
      html: createOrderShippedEmail(orderData, orderNumber, locale),
    },
    apiUrl
  );
};
